version: 2.0

references:
  mac: &mac
      macos:
        xcode: '10.1.0'
      working_directory: ~/getenvoy

jobs:
  check:
    <<: *mac
    steps:
      - checkout
      - run: git status
      - run: |
          for f in $( ls ./Formula/*.rb ); do
            brew audit $f
            brew install -v $f
            brew test $f
            brew uninstall $f
          done
